### ISSUE TITLE
Fix the sortx argument in pirateplot()

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/yarrr#32]
The `sortx` argument, which should allow the user to specify how categories are ordered, is currently not working.

**Comment by tcashby** [comment]
Has this ever been addressed? If not is there a workaround?

**Comment by ndphillips** [comment]
@tcashby Thanks for the bump. I think I just fixed it in version 0.1.5. Please install the latest version from github with `devtools::install_github('ndphillips/yarrr')` and let me know if it works.

**Comment by tcashby** [comment]
First off, thanks for the rapid turnaround. However, it seems like I'm still getting the error.

Here's the code I'm using:
pirateplot(VAF~GENE, data=mutations, xlab = "Gene symbol", ylab = "VAF", sortx="s")

I get this error:
Error in lapply(X = X, FUN = FUN, ...) : object 'iv.levels' not found

With this code:
pirateplot(VAF~GENE, data=mutations, xlab = "Gene symbol", ylab = "VAF", sortx="a")

I get this error:
Error in lapply(X = X, FUN = FUN, ...) : object 'iv.levels' not found

With this code:
pirateplot(VAF~GENE, data=mutations, xlab = "Gene symbol", ylab = "VAF", sortx="mean")

I get this error:
Error in ncol(agg) : object 'agg' not found

Leaving off the sortx like this works as intended:
pirateplot(VAF~GENE, data=mutations, xlab = "Gene symbol", ylab = "VAF")

**Comment by ndphillips** [comment]
Two points:

there was indeed a second bug with the "agg" value I think I fixed

Also from now on you can't use "s",  or "a" you have to write "sequential", or "alphabetical", 

Please try reinstalling and see if that fixes it!

**Comment by ndphillips** [comment]
I think this has been fixed so I will close this now. If it's not, please reopen and let me know.
