### ISSUE TITLE
Error when not enough data in one of the "bins"

### ISSUE THREAD

**Issue by nuskcalb** [ndphillips/yarrr#7]
When trying to plot DV ~ IV1 + IV2, sometimes one of the "bins" does not have enough data and Pirate plot gives an error:

> Error in t.test.default(dv.i, conf.level = inf.p) : not enough 'x' observations

Would it be possible to show the plot, leaving a blank space (with the proper title of course) where we don't have enough data?

**Comment by ndphillips** [comment]
Hmmm, this is an issue that I thought I had fixed in the latest version of the package. Could you make sure you have the latest version (sadly I haven't been good about updating the version numbers) and see if that fixes it?

**Comment by nuskcalb** [comment]
Hi!

I reinstalled devtools and yarrr and the error persists.

I created a "reproducible" example so you can take a look. As you can see in the attached R script (hopefully) , the first plot works fine, but the second gives an error. Please, let me know if there is anything unclear.

[Pirate - error.zip](https://github.com/ndphillips/yarrr/files/398193/Pirate.-.error.zip)

Thanks!

**Comment by ndphillips** [comment]
Thanks for catching the bug! I think I fixed it. Try installing it again and see how it goes...

**Comment by nuskcalb** [comment]
Works great. Thanks! And congrats on the beautiful Pirate plots!

**Comment by ndphillips** [comment]
thanks!
